version: 2
jobs:
  build:    
    working_directory: ~/esl
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: esl-{{ checksum "pom.xml" }}      
      - run: mvn dependency:go-offline      
      - save_cache:
          paths:
            - ~/.m2
          key: esl-{{ checksum "pom.xml" }}      
      - run: mvn resources:resources package      
      - store_test_results:
          path: target/surefire-reports      
      - store_artifacts:
          path: target/esl.jar
      - setup_remote_docker
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM         
          docker build -t thcathy/esl:$TAG -f docker/Dockerfile .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push thcathy/esl:$TAG
          
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 5 * * 5"
          filters:
            branches:
              only: 
                - master
    jobs:
      - build
